export interface CelebrityOfferConstant {
  offerCode: string;
  offerReceivedDate: string;
  offerExpirationDate: string;
  offerName: string;
  shipClass: string;
  ship: string;
  sailDate: string;
  departurePort: string;
  nights: number;
  itinerary: string;
  roomCategory: string;
  guests: string;
  perks: string | null;
}

export const CELEBRITY_OFFER_CONSTANTS: CelebrityOfferConstant[] = [
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-01-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Solstice', ship: 'Celebrity Eclipse', sailDate: '11-12-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-20-2025', departurePort: 'Athens (Piraeus), Greece', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '11-21-2025', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '11-24-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-24-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '11-28-2025', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25LKY1503', offerReceivedDate: '10-23-2025', offerExpirationDate: '11-02-2025', offerName: 'Lucky Picks', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-29-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-01-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-06-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Eclipse', sailDate: '11-12-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-20-2025', departurePort: 'Athens (Piraeus), Greece', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '11-21-2025', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '11-24-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-24-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '11-28-2025', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-29-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-01-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '12-04-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-05-2025', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-08-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '12-08-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-12-2025', departurePort: 'Buenos Aires, Argentina', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '12-13-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-15-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-19-2025', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25PRS104', offerReceivedDate: '10-22-2025', offerExpirationDate: '11-05-2025', offerName: 'Power Play', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-26-2025', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Veranda', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Silhouette', sailDate: '11-01-2025', departurePort: 'Miami, Florida', nights: 8, itinerary: 'Aruba, Curacao  Bonaire Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Eclipse', sailDate: '11-12-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Constellation', sailDate: '11-23-2025', departurePort: 'Tampa, Florida', nights: 7, itinerary: 'Western Caribbean', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '11-29-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-01-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '12-04-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Constellation', sailDate: '12-07-2025', departurePort: 'Tampa, Florida', nights: 7, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-08-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '12-13-2025', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Constellation', sailDate: '12-14-2025', departurePort: 'Tampa, Florida', nights: 7, itinerary: 'Western Caribbean Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '12-15-2025', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Constellation', sailDate: '01-04-2026', departurePort: 'Tampa, Florida', nights: 7, itinerary: 'Western Caribbean  Bahamas', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Silhouette', sailDate: '01-04-2026', departurePort: 'Fort Lauderdale, Florida', nights: 6, itinerary: 'Grand Cayman, Mexico  Key West', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '01-05-2026', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Constellation', sailDate: '01-11-2026', departurePort: 'Tampa, Florida', nights: 7, itinerary: 'Western Caribbean Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Edge', ship: 'Celebrity Beyond', sailDate: '01-18-2026', departurePort: 'Miami, Florida', nights: 7, itinerary: 'St. Thomas, St. Kitts  Puerto Plata', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Silhouette', sailDate: '02-01-2026', departurePort: 'Fort Lauderdale, Florida', nights: 6, itinerary: 'Grand Cayman, Mexico  Key West', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '02-02-2026', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Bahamas  Perfect Day Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '02-23-2026', departurePort: 'Fort Lauderdale, Florida', nights: 4, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Constellation', sailDate: '03-01-2026', departurePort: 'Tampa, Florida', nights: 7, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Solstice', ship: 'Celebrity Reflection', sailDate: '03-06-2026', departurePort: 'Fort Lauderdale, Florida', nights: 3, itinerary: 'Key West  Bahamas Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '03-07-2026', departurePort: 'Fort Lauderdale, Florida', nights: 7, itinerary: 'Bahamas  Grand Turk Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '03-21-2026', departurePort: 'Fort Lauderdale, Florida', nights: 7, itinerary: 'Western Caribbean Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Constellation', sailDate: '03-22-2026', departurePort: 'Tampa, Florida', nights: 7, itinerary: 'Western Caribbean Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Millennium', ship: 'Celebrity Summit', sailDate: '04-04-2026', departurePort: 'Fort Lauderdale, Florida', nights: 5, itinerary: 'Bahamas Getaway Cruise', roomCategory: 'Inside', guests: '2 Guests', perks: null },
  { offerCode: '25CGY607', offerReceivedDate: '10-06-2025', offerExpirationDate: '10-30-2025', offerName: 'Paradise Payouts', shipClass: 'Edge', ship: 'Celebrity Beyond', sailDate: '04-26-2026', departurePort: 'Miami, Florida', nights: 7, itinerary: 'San Juan,grand Turk,dr  Perfect Day', roomCategory: 'Inside', guests: '2 Guests', perks: null },
];
