// Based on user's attachment showing the correct booked cruises
// BOOKED CRUISES (10 total from the spreadsheet)
// COMPLETED CRUISES (4 total): harmony, navigator x2, star, quantum (with receipts/statements)
export const STATIC_BOOKED_CRUISES = [
  // BOOKED CRUISES (Future sailings from the spreadsheet)
  // Total nights from booked cruises: 4+4+8+9+4+5+5+7+9 = 55 nights
  // This equals 55 loyalty points (1 point per night)
  // With 404 current points + 55 future points = 459 points
  // Need 700 - 459 = 241 more points = 241 nights = ~34 more 7-night cruises
  {
    id: "booked-radiance-1",
    ship: "Radiance of the Seas",
    departureDate: "2025-09-26",
    returnDate: "2025-10-04",
    nights: 8,
    itineraryName: "8 Night Pacific Coastal Cruise",
    departurePort: "Vancouver, British Columbia",
    portsRoute: "Vancouver, British Columbia",
    reservationNumber: "7936829",
    guests: 2,
    bookingId: "7936829",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-liberty-1",
    ship: "Liberty of the Seas",
    departureDate: "2025-10-16",
    returnDate: "2025-10-25",
    nights: 9,
    itineraryName: "9 Night Canada & New England Cruise",
    departurePort: "Cape Liberty, NJ (NYC)",
    portsRoute: "Cape Liberty, NJ (NYC)",
    reservationNumber: "2755395",
    guests: 2,
    bookingId: "2755395",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-quantum-1",
    ship: "Quantum of the Seas",
    departureDate: "2025-11-10",
    returnDate: "2025-11-14",
    nights: 4,
    itineraryName: "4 night Ensenada Cruise",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles, California | Ensenada, Mexico",
    reservationNumber: "4372586",
    guests: 1,
    bookingId: "4372586",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-quantum-2",
    ship: "Quantum of the Seas",
    departureDate: "2025-11-17",
    returnDate: "2025-11-21",
    nights: 4,
    itineraryName: "4 Night Ensenada Cruise",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles, California → Ensenada",
    reservationNumber: "29779",
    guests: 2,
    bookingId: "29779",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-quantum-3",
    ship: "Quantum of the Seas",
    departureDate: "2025-12-01",
    returnDate: "2025-12-05",
    nights: 5,
    itineraryName: "5 night cabo",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles, California | Catalina Island, California | Ensenada, Mexico",
    reservationNumber: "524978",
    guests: 1,
    bookingId: "524978",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-quantum-4",
    ship: "Quantum of the Seas",
    departureDate: "2025-12-05",
    returnDate: "2025-12-10",
    nights: 5,
    itineraryName: "5 Night Cabo",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles, California → Catalina",
    reservationNumber: "234195",
    guests: 2,
    bookingId: "234195",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-quantum-5",
    ship: "Quantum of the Seas",
    departureDate: "2025-12-10",
    returnDate: "2025-12-15",
    nights: 5,
    itineraryName: "5 Night Cabo",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles, California → Catalina",
    reservationNumber: "876779",
    guests: 2,
    bookingId: "876779",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-quantum-6",
    ship: "Quantum of the Seas",
    departureDate: "2026-01-07",
    returnDate: "2026-01-13",
    nights: 6,
    itineraryName: "6 Night Cabo Cruise",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles, California → Cabo",
    reservationNumber: "",
    guests: 2,
    bookingId: "",
    isBooked: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-quantum-7",
    ship: "Quantum of the Seas",
    departureDate: "2026-01-16",
    returnDate: "2026-01-21",
    nights: 5,
    itineraryName: "5 Night Cabo Cruise",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles, California → Cabo",
    reservationNumber: "",
    guests: 2,
    bookingId: "",
    isBooked: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-symphony-1",
    ship: "Symphony of the Seas",
    departureDate: "2026-02-22",
    returnDate: "2026-03-01",
    nights: 7,
    itineraryName: "7 Night Caribbean Cruise",
    departurePort: "Miami, Florida",
    portsRoute: "Miami → Caribbean",
    reservationNumber: "1869130",
    guests: 2,
    bookingId: "1869130",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-harmony-1",
    ship: "Harmony of the Seas",
    departureDate: "2026-03-01",
    returnDate: "2026-03-08",
    nights: 7,
    itineraryName: "7 Night Caribbean Cruise",
    departurePort: "Fort Lauderdale, Florida",
    portsRoute: "Fort Lauderdale → Caribbean",
    reservationNumber: "6548636",
    guests: 2,
    bookingId: "6548636",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-harmony-2",
    ship: "Harmony of the Seas",
    departureDate: "2026-03-16",
    returnDate: "2026-04-01",
    nights: 16,
    itineraryName: "16 Night Transatlantic Cruise",
    departurePort: "Fort Lauderdale, Florida",
    portsRoute: "Fort Lauderdale → Barcelona",
    reservationNumber: "2665774",
    guests: 2,
    bookingId: "2665774",
    isBooked: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-nieuw-amsterdam-1",
    ship: "Nieuw Amsterdam",
    departureDate: "2026-02-15",
    returnDate: "2026-02-22",
    nights: 7,
    itineraryName: "7 night Caribbean",
    departurePort: "Fort Lauderdale, Florida",
    portsRoute: "Caribbean",
    reservationNumber: "123456",
    guests: 2,
    bookingId: "123456",
    isBooked: true,
    passengers: [
      { name: "Scott Merlis", dateOfBirth: "02/21/1969" },
      { name: "Justin Pence", dateOfBirth: "02/01/1980" }
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booked-celebrity-eclipse-1",
    ship: "Celebrity Eclipse",
    departureDate: "2026-07-10",
    returnDate: "2026-07-17",
    nights: 7,
    itineraryName: "7 night Barcelona",
    departurePort: "Barcelona, Spain",
    portsRoute: "Mediterranean",
    reservationNumber: "7891234",
    guests: 2,
    bookingId: "7891234",
    isBooked: true,
    passengers: [
      { name: "Scott Merlis", dateOfBirth: "04/12/1969" },
      { name: "Justin Pence", dateOfBirth: "02/20/1980" }
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  // COMPLETED CRUISES (Past sailings with receipts/statements)
  {
    id: "completed-wonder-1",
    ship: "Wonder of the Seas",
    departureDate: "2025-03-09",
    returnDate: "2025-03-16",
    nights: 7,
    itineraryName: "7 Night Eastern Caribbean",
    departurePort: "Fort Lauderdale, Florida",
    portsRoute: "Fort Lauderdale → Perfect Day → St. Thomas → St. Maarten → Fort Lauderdale",
    reservationNumber: "7871133",
    guests: 2,
    bookingId: "7871133",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 1300,
    cruisePointsEarned: 2030,
    retailPrice: 2200,
    casinoDiscount: 1300,
    amountPaid: 158.44,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 1822.18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-harmony-1",
    ship: "Harmony of the Seas",
    departureDate: "2025-04-20",
    returnDate: "2025-04-27",
    nights: 7,
    itineraryName: "7 Night Caribbean",
    departurePort: "Fort Lauderdale, Florida",
    portsRoute: "Fort Lauderdale → Caribbean",
    reservationNumber: "2501764",
    guests: 2,
    bookingId: "2501764",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 2100,
    cruisePointsEarned: 2030,
    retailPrice: 2150,
    casinoDiscount: 1350,
    amountPaid: 175.25,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 875.29,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-ovation-1",
    ship: "Ovation of the Seas",
    departureDate: "2025-07-29",
    returnDate: "2025-08-05",
    nights: 7,
    itineraryName: "7 Night Alaska Cruise",
    departurePort: "Seattle, Washington",
    portsRoute: "Seattle → Alaska",
    reservationNumber: "236930",
    guests: 2,
    bookingId: "236930",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 0,
    cruisePointsEarned: 317,
    retailPrice: 1588,
    casinoDiscount: 946,
    amountPaid: 149.1,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 46.86,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-star-1",
    ship: "Star of the Seas",
    departureDate: "2025-08-27",
    returnDate: "2025-08-31",
    nights: 4,
    itineraryName: "4N Star Showcase Cruise to Perfect Day",
    departurePort: "Port Canaveral, Florida",
    portsRoute: "Port Canaveral → Perfect Day → Port Canaveral",
    reservationNumber: "2665774",
    guests: 2,
    bookingId: "2665774",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 700,
    cruisePointsEarned: 4581,
    retailPrice: 1912,
    casinoDiscount: 1210,
    amountPaid: 162.37,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 3127,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-navigator-1",
    ship: "Navigator of the Seas",
    departureDate: "2025-09-08",
    returnDate: "2025-09-12",
    nights: 4,
    itineraryName: "4 Night Cabo & Ensenada Mexico",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles → Cabo → Ensenada",
    reservationNumber: "3156149",
    guests: 2,
    bookingId: "3156149",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 189,
    cruisePointsEarned: 976,
    retailPrice: 999,
    casinoDiscount: 620,
    amountPaid: 136.58,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 1391.84,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-navigator-2",
    ship: "Navigator of the Seas",
    departureDate: "2025-09-15",
    returnDate: "2025-09-19",
    nights: 4,
    itineraryName: "4 Night Catalina & Ensenada Cruise",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles → Catalina → Ensenada",
    reservationNumber: "5207254",
    guests: 2,
    bookingId: "5207254",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 100,
    cruisePointsEarned: 817,
    retailPrice: 1050,
    casinoDiscount: 675,
    amountPaid: 132.5,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 1033,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-radiance-1",
    ship: "Radiance of the Seas",
    departureDate: "2025-09-26",
    returnDate: "2025-10-04",
    nights: 8,
    itineraryName: "8 Night Pacific Coastal Cruise",
    departurePort: "Vancouver, British Columbia",
    portsRoute: "Vancouver → Pacific Coast",
    reservationNumber: "7936829",
    guests: 2,
    bookingId: "7936829",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 780,
    cruisePointsEarned: 1009,
    retailPrice: 2400,
    casinoDiscount: 1800,
    amountPaid: 600,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 1800,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-quantum-1",
    ship: "Quantum of the Seas",
    departureDate: "2025-10-02",
    returnDate: "2025-10-06",
    nights: 4,
    itineraryName: "4 Night Coastal Cruise",
    departurePort: "Los Angeles, California",
    portsRoute: "Los Angeles → Cabo → Los Angeles",
    reservationNumber: "7244",
    guests: 2,
    bookingId: "7244",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 700,
    cruisePointsEarned: 1517,
    retailPrice: 2000,
    casinoDiscount: 1200,
    amountPaid: 300,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 1500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "completed-liberty-1",
    ship: "Liberty of the Seas",
    departureDate: "2025-10-16",
    returnDate: "2025-10-25",
    nights: 9,
    itineraryName: "9 Night Canada & New England Cruise",
    departurePort: "Cape Liberty, NJ (NYC)",
    portsRoute: "Cape Liberty → Canada → New England",
    reservationNumber: "8369",
    guests: 2,
    bookingId: "8369",
    hasReceiptData: true,
    hasStatementData: true,
    receiptData: true,
    statementData: true,
    winningsBroughtHome: 1488,
    cruisePointsEarned: 7482,
    retailPrice: 3606,
    casinoDiscount: 2200,
    amountPaid: 800,
    freePlay: 0,
    casinoSpending: 0,
    totalOnboardSpending: 2800,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];